name: egeria-ui-components

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.0
      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.13.0"
      - name: Report npm and node version
        run: |
          node -v
          npm -v
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
        env:
          NODE_OPTIONS: "--max_old_space_size=6144"
